name: My second Workflow

on:
  push:
    paths:
      - '.github/workflows/second.yml'

jobs:
  pehla_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "Hi, Welcome! This is the test workflow!"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Commands
        run: |
          echo "Listing files:"
          ls -lrth
          echo "--------------------------------"
          echo "Disk usage:"
          df -h
          echo "--------------------------------"
          echo "Displaying README.md:"

      - name: Generate ACSII Artwork
        run: cowsay -f dragon "Run for cover,I am a DRAGON....RAWR" >> dragon.txt
