name : 1st Workflow

on:
    push
jobs:
    os_check:
        runs-on: ubuntu-latest
        steps:
            - name: Os Version
              run: lsb_release -a
    list_dir:
        runs-on: ubuntu-latest
        needs: os_check
        steps:
            - name: List all the dirs
              run: ls /            
    check_home:
        runs-on: ubuntu-latest
        needs: os_check
        steps:
            - name: List of accounts
              run: ls /home      
    check_etc:
        runs-on: ubuntu-latest
        needs: list_dir
        steps:
            - name: List of config files
              run: ls /etc
    whoami:
        runs-on: ubuntu-latest
        needs: [check_home , check_etc , os_check , list_dir]
        steps:
            - name: check account name
              run: whoami                 