name : 1st Workflow

on:
    push
jobs:
    os_check:
        runs-on: ubuntu-latest
        steps:
            - name: Os Version
              run: lsb_release -a
    list_dir:
        runs-on: ubuntu-latest
        steps:
            - name: List all the dirs
              run: ls /            
