name: Generate ASCII Artwork

on:
  workflow_dispatch: 
  push:
    paths:
      - '.github/workflows/generate.yml'
      - 'ascii.sh'

jobs:
  ascii_job:
    runs-on: mine
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
      cancel-in-progress: true
    steps:
      - name: whoami
        run: whoami
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -lrth
      
      - name: Execute Shell Script!
        run:  bash ascii.sh
      - name: soja beta
        run:  sleep 400


