name: Generate ASCII Artwork

on:
  workflow_dispatch: 
  push:
    paths:
      - '.github/workflows/generate.yml'
      - 'ascii.sh'

jobs:
  ascii_job:
    runs-on: self-hosted
    steps:
      - name: whoami
        run: whoami
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -lrth
      
      - name: Execute Shell Script!
        run:  bash ascii.sh


